# -*- coding: utf-8 -*-
"""Etudier_le_Japon .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RCrcYmZVl-b1ORBuDaA8lLyZwyllfyTY
"""

!git clone https://github.com/conanak99/jav-py.git

import pandas as pd #ham chua nhieu cong cu de analysée data
import warnings 
warnings.filterwarnings('ignore')
import seaborn as sns # dung de ve bieu do (dep hon)
import matplotlib.pyplot as plt #(cung dung de ve bieu do)

actress = pd.read_json("jav-py/acctress.json") # doc file json
actress.head() #hien thi 1 vai ten trong danh sach

actress.info() # trich xuat toan bo du lieu

# tinh toan xu ly va ve bieu do tuoi
actress['birthday'] = pd.to_datetime(actress['birthday'], yearfirst = True)
actress['age'] = 2021 - pd.DatetimeIndex(actress['birthday']).year

actress .head()

actress.age.min()

actress[actress['age'] == actress.age.min()]
#dung ham: ![ten](link)--> de hien thi anh nhu duoi

"""![takeda erena](https://mblogthumb-phinf.pstatic.net/MjAyMDA1MzFfMjEw/MDAxNTkwOTM2MTY3OTgx.PjrEOKxKzG3_7Vc372uzsfhUgeRBL2qEWmTwKHlOwd0g.Nf5NAjYpOyNfkc1SmV83VyCDcg0igxIwpPlZXC4CK-4g.JPEG.world199/1590936167024.jpg?type=w800)

![mika](https://w.wallha.com/ws/8/pegFOkLq.jpg)
"""

# tinh do tuoi trung binh
actress.describe()

actress.info()

plt.figure(figsize = (15,10))
sns.displot(actress.age)

plt.figure(figsize = (15,10)) # figure size: 15,10 = 1080*720
sns.displot(actress.age.dropna())  #ham dropna --> loai bo nhung ten khong co trong danh sach

actress.describe()# récupéter tous les données

actress.head()

actress.age.max()

actress.bust.hist(figsize=(15,6), bins= 50) # bins= 50 colone

actress.bust.head()

actress.bust.describe()#.max()

actress[actress.name.str.contains("Yui")]

actress[actress.name.str.contains("Mikami")]

"""![mikami](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTbrqx4Oe77lZs0AvQ5Z_DUArJvtE5y-meGqOAe-0WMkiotMj2WxBUoWMj_y4txE3Q8L2g&usqp=CAU)"""

actress.info()

from wordcloud import WordCloud

hobby_df = actress[actress.hobby.notnull()]

hobby_df.info()

hobby_txt = ''.join(hobby_df['hobby'])

from matplotlib import rcParams
rcParams['figure.figsize'] = 15,8
wordcloud = WordCloud(font_path='jav-py/jp.otf', max_words=200, max_font_size=40, scale=3).gerenate(hobby_txt)

plt.imshow(wordcloud)
plt.axis('off')
plt.show()

from google.colab import drive
drive.mount('/content/drive')